name: Bootcamp 2020  urdu

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing node 
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
        

    
    - name: Installing surge
      run: npm install --globle surge
    
    - name: deploying using surge
      run: surge ./ blushing-store.surge.sh --token "71a6f2d20f9b5770c48a34f6bc642476"

      
      
      
