name: Bootcamp 2020  urdu

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing node 
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
        

    
    - name: Installing surge
      run: npm install --globle surge
    
    - name: desploying using surge
      run: surge ./ ahsanjamil305.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      
      
      
